#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

ynh_config_remove_systemd
ynh_config_remove_nginx
