#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Stopping slskdN..."
ynh_systemctl --service="$app" --action="stop"

ynh_script_progression "Upgrading slskdN..."
ynh_setup_source --dest_dir="$install_dir" --full_replace
chown -R root:"$app" "$install_dir"
chmod -R u=rwX,g=rX,o= "$install_dir"
chmod 750 "$install_dir/slskd"
patch_lttng_soname

if [ ! -e "/var/log/$app/$app.log" ]; then
    install -d -m 0750 -o "$app" -g "$app" "/var/log/$app"
    install -m 0640 -o "$app" -g "$app" /dev/null "/var/log/$app/$app.log"
fi

ynh_config_add_nginx
ynh_config_add_systemd
ynh_config_add_logrotate

yunohost service add "$app" \
    --description="Soulseek client and server" \
    --log="/var/log/$app/$app.log" \
    --needs_exposed_ports="$port_soulseek"

ynh_systemctl --service="$app" --action="start"
ynh_script_progression "Upgrade of slskdN completed"
